import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "./components/AuthProvider"; // Corrected path

export const metadata: Metadata = {
  title: "Tree Traction Zips",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
